### PR TITLE
Add support for JMS (HornetQ) queue

### PR DESCRIPTION
**Pull request by hcherukuri**
I see an error "fatal: [localhost]: FAILED! => {"msg": "'list object' has no attribute 'queue_address'"}"

### CODE REVIEW

**Comment by rpelisse** [comment]
Cool! Let me look at that and see if I can figure out the issue.

**Comment by rpelisse** [comment]
@hcherukuri oh, CI fails because the documentation is missing. Can you add that ? This way at least we'll see if the other sanity test does not put us on the right direction.

**Comment by hcherukuri** [comment]
Ok will add the documentation.

**Comment by hcherukuri** [comment]
looks like the tests are ok.

**Comment by rpelisse** [comment]
@hcherukuri I've the same issue locally, let me see if I can fix it for you ;) !

**Comment by rpelisse** [comment]
@hcherukuri Found it! Funnily enough, I ran into this issue recently. When you defined the jms: subsystems you defined its content as a list, so you need to iterate on the list in the template, otherwise, it won't work. The error message actually refers to that: list of items in the subsystem jms does NOT have an attribute queue_address, but each item in the list have this attribute!

```
diff --git a/plugins/templates/rules/jms.j2 b/plugins/templates/rules/jms.j2
index 6e99f0f..7e813cc 100644
--- a/plugins/templates/rules/jms.j2
+++ b/plugins/templates/rules/jms.j2
@@ -1,8 +1,10 @@
 { "jms-queue" => {
-  "{{ values['queue_address'] }}" => {
-    "entries" => "{{ values['entries'] }}",
-    "durable" => "{{ values['durable'] }}"
+  {% for item in values %}
+  "{{ item['queue_address'] }}" => {
+    "entries" => "{{ item['entries'] }}",
+    "durable" => "{{ item['durable'] }}"
     }
   }
+  {% endfor %}
 }
 ```

I did not figure out if I could update your PR directly, so I simply added the change above. So now you can update your PR and see if it works :)

**Comment by hcherukuri** [comment]
@rpelisse I tried this way, it didn't seem to work before, let me recheck.

**Comment by hcherukuri** [comment]
---
- hosts: localhost
  gather_facts: True
  vars:
    app_url: http://people.redhat.com/~rpelisse/simple-webapp.war
    app: /tmp/simple-webapp.war
    jboss_home: /home/hcheruku/Projects/jboss-eap-6.4
  collections:
    - redhat.jcliff
  roles:
    - jcliff
  tasks:
    - jcliff:
        wfly_home: "{{ jboss_home }}"
        subsystems:
          - jms:
              - queue_address: myQueue
                entries: [queue/myQueue jms/queue/myQueue java:jboss/exported/jms/queue/myQueue]
                durable: True

**Comment by hcherukuri** [comment]
---
- hosts: localhost
  gather_facts: True
  vars:
    app_url: http://people.redhat.com/~rpelisse/simple-webapp.war
    app: /tmp/simple-webapp.war
    jboss_home: /home/hcheruku/Projects/jboss-eap-6.4
  collections:
    - redhat.jcliff
  roles:
    - jcliff
  tasks:
    - jcliff:
        wfly_home: "{{ jboss_home }}"
        subsystems:
          - jms:
              - queue_address: myQueue
                entries: [queue/myQueue jms/queue/myQueue java:jboss/exported/jms/queue/myQueue]
                durable: True

    - name: "Restart Wildfly"
      command: "{{ jboss_home }}/bin/jboss-cli.sh --connect --command=':reload'"
      register: cli_result

**Comment by hcherukuri** [comment]
It should get added under here.

<jms-destinations>
                    <jms-queue name="ExpiryQueue">
                        <entry name="java:/jms/queue/ExpiryQueue"/>
                    </jms-queue>
                    <jms-queue name="DLQ">
                        <entry name="java:/jms/queue/DLQ"/>
                    </jms-queue>
                </jms-destinations>

**Comment by rpelisse** [comment]
@hcherukuri thanks for the playbook! However, I'm surprised it works for you because, on my side, I get a syntax error:

```
The offending line appears to be:

              - queue_address: myQueue
                entries: [queue/myQueue jms/queue/myQueue java:jboss/exported/jms/queue/myQueue]
                                                              ^ here
```

I've tried several syntax (adding commas, doubles quotes,...) but it always end up in an invalid file being generated (meaning the file Jinja is generating for JCliff is not valid for jcliff). 

Also, the "entries" should be a list rather than a string (str), so that one can use the following syntax:

```
The offending line appears to be:

              - queue_address: myQueue
                entries: 
                  - queue/myQueue jms/queue/myQueue 
                  - java:jboss/exported/jms/queue/myQueue
```

But this syntax is also leading to invalid file being generated. So, work in progress on my side :)

**Comment by rpelisse** [comment]
superseded by #24

**Pull request closed without merging**
