### PR TITLE
Adds remote destination for standard sockets and modcluster support

### PR DESCRIPTION
**Pull request by sabre1041**
Adds remote destination for standard sockets and modcluster support

### CODE REVIEW

**Comment by rpelisse** [comment]
FYI, this PR is dependant on this [PR against JCliff](https://github.com/bserdar/jcliff/pull/100).

**Comment by rpelisse** [comment]
LGTM and works for me. @hcherukuri let me know if it also works for you, we'll merge then.

**Comment by hcherukuri** [comment]
http://pastebin.test.redhat.com/925085, works for me.

**Review by hcherukuri — APPROVED** [review]

**Comment by rpelisse** [comment]
@sabre1041 @hcherukuri I think we need to release JCliff before merging this change (for clarity purpose). It might be also a goo time to (maybe) start tying the collection to a specific version of JCliff ?

**Pull request merged**
